version: "3.9"
services:
  Streamserver:
    image: stream_container
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - "HOST=storage"
    volumes:
      - ./:/app
  storage:
    image: quay.io/minio/minio 
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    command: " server /data --console-address ':9001'"
    